### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by souhailaS** [antoniogarmendia/generatePalleteAutomatically#1]
There are some plugins that are referenced in the dependencies , but not found .

**Comment by antoniogarmendia** [comment]
Hi, if you have any problem, please, do not hesitate to contact me. Cheers, Antonio

**Comment by souhailaS** [comment]
Hi , Thank you !  I couldn't find the needed plugins in the beginning.  Everything is fine now.
Souhaila.
